# warning - contains secrets
QUARKUS_DATASOURCE_DB_KIND: postgresql
QUARKUS_DATASOURCE_USERNAME: oikos_owner
QUARKUS_DATASOURCE_PASSWORD: ZObeH5mlJkN2
QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://ep-white-rice-a2dbj7mv.eu-central-1.aws.neon.tech/oikos?sslmode=require

# see https://quarkus.io/guides/hibernate-orm to improve config
QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
  
ADMIN_USERNAME: cyriloulou 
ADMIN_PASSWORD: fK6DWP4nWFCSyeA9bWfG31Twx

